-define(GhcBomeApiUsage,
    "PUT /v1/users/:id~n"
    "{~n"
    "    \"<metric_name1>\" : <metric_value1>,~n"
    "    ...~n"
    "    \"<metric_nameN>\" : <metric_valueN>~n"
    "}~n"
    "~n"
    "GET /v1/users/:id[?filter=metric_name1,...,metric_nameN]~n"
    "~n"
    "PATCH /v1/users/:id~n"
    "{~n"
    "    \"<metric_name1>\" : <metric_value1>,~n"
    "    ...~n"
    "    \"<metric_nameN>\" : <metric_valueN>~n"
    "}~n"
    "~n"
    "DELETE /v1/users/:id~n"
    "[~n"
    "    \"<metric_name1>\",~n"
    "    ...~n"
    "    \"<metric_nameN>\"~n"
    "]~n"
).
