-define(GhcBomeApiUsage,
    "PUT /v1/users/:id~n"
    "{~n"
    "    \"<type1>\" : <value1>,~n"
    "    ...~n"
    "    \"<typeN>\" : <valueN>~n"
    "}~n"
    "~n"
    "GET /v1/users/:id[?filter=type1,...,typeN]~n"
    "~n"
    "PATCH /v1/users/:id~n"
    "{~n"
    "    \"<type1>\" : <value1>,~n"
    "    ...~n"
    "    \"<typeN>\" : <valueN>~n"
    "}~n"
    "~n"
    "DELETE /v1/users/:id~n"
    "[~n"
    "    \"<type1>\",~n"
    "    ...~n"
    "    \"<typeN>\"~n"
    "]~n"
).
